### ISSUE TITLE
install package failed

### ISSUE THREAD

**Issue by huiwenzhang** [GeigenPrinzipal/afCEC#1]
Hi, when I tried to install your afCEC package with devtools and use command `install_github("GeigenPrinzipal/afCEC")`. I successfully download the code but the compile failed with the error:
```
Parser.cpp:1:22: fatal error: .\Parser.h: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:168: recipe for target 'Parser.o' failed
make: *** [Parser.o] Error 1
ERROR: compilation failed for package ‘afCEC’
* removing ‘/home/huiwen/R/x86_64-pc-linux-gnu-library/3.4/afCEC’
Installation failed: Command failed (1)
```
How could I fix this? THX

**Comment by KByrski** [comment]
Dear Mr. Huiwen Zhang,

Thank You for Your remark. Unfortunately, I am afraid I wouldn't be able to help You, since so far I haven't used the devtools at all. I suggest You to download the binary package and theninstall it from the R-level using the command line script: install.packages(<path of the binary package>).

Best regards,

Krzysztof Byrski

**Comment by przem85** [comment]
The afCEC package is a part of CRAN repository and it can be installed by the following command:

install.packages("afCEC")
library("afCEC")

The basic usage comes down to the function afCEC with two required arguments: input data (points) and the initial number of centers (maxClusters):

afCEC (points= , maxClusters= )

**Comment by huiwenzhang** [comment]
Thx.
